# Generated by Django 5.2.8 on 2025-12-01 17:55

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('user_tags', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAddresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(db_index=True, max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Email Address',
                'verbose_name_plural': 'Email Addresses',
            },
        ),
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the email account.', max_length=255, verbose_name='Account Name')),
                ('_content_type', models.ForeignKey(help_text='The content type of the email account.', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
                ('user', models.OneToOneField(help_text='The user associated with this email account.', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Email Account',
                'verbose_name_plural': 'Email Accounts',
            },
        ),
        migrations.CreateModel(
            name='EmailFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_name', models.CharField(db_index=True, editable=False, max_length=255, unique=True)),
                ('account', models.ForeignKey(editable=False, help_text='The email account associated with this folder.', on_delete=django.db.models.deletion.CASCADE, related_name='email_folders', to='emails.emailaccount', verbose_name='Email Account')),
                ('parent', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='emails.emailfolder')),
            ],
            options={
                'verbose_name': 'Email Folder',
                'verbose_name_plural': 'Email Folders',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('message_id', models.CharField(db_index=True, help_text='The unique message ID of the email.', max_length=255, primary_key=True, serialize=False, unique=True, verbose_name='Message ID')),
                ('json_data', models.JSONField(editable=False)),
                ('date_received', models.DateTimeField(editable=False, help_text='The date and time the email was received.', verbose_name='Date Received')),
                ('date_sent', models.DateTimeField(editable=False, help_text='The date and time the email was sent.', verbose_name='Date Sent')),
                ('body_text', models.TextField(blank=True, default='', editable=False, help_text='The plain text body of the email.', verbose_name='Body Text')),
                ('body_html', models.TextField(blank=True, default='', editable=False, help_text='The HTML body of the email.', verbose_name='Body HTML')),
                ('is_read', models.BooleanField(default=False, editable=False, help_text='Whether the email has been read.', verbose_name='Is Read')),
                ('priority', models.IntegerField(blank=True, editable=False, help_text='The priority of the email.', null=True, verbose_name='Priority')),
                ('subject', models.CharField(editable=False, help_text='The subject of the email.', max_length=255, verbose_name='Subject')),
                ('in_reply_to', models.ForeignKey(blank=True, editable=False, help_text='The email this message is replying to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='emails.email', verbose_name='In-Reply-To')),
                ('from_address', models.ForeignKey(editable=False, help_text='The email address of the sender.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_from', to='emails.emailaddresses', verbose_name='From Address')),
                ('reply_to_address', models.ForeignKey(blank=True, editable=False, help_text='The email address to reply to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails_reply_to', to='emails.emailaddresses', verbose_name='Reply-To Address')),
                ('to_addresses', models.ManyToManyField(editable=False, help_text='The email addresses of the primary recipients.', related_name='emails_to', to='emails.emailaddresses', verbose_name='To Addresses')),
                ('folder', models.ForeignKey(blank=True, editable=False, help_text='The folder the email is stored in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emails', to='emails.emailfolder', verbose_name='Folder')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
            },
        ),
        migrations.CreateModel(
            name='EmailFolderPersonalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_color', models.CharField(blank=True, default='', help_text='The display color for this email folder in HEX format.', max_length=7, verbose_name='Display Color')),
                ('display_name', models.CharField(blank=True, default='', help_text='The display name for this email folder.', max_length=255, verbose_name='Display Name')),
                ('folder', models.OneToOneField(editable=False, help_text='The email folder associated with this personalization.', on_delete=django.db.models.deletion.CASCADE, related_name='personalization', to='emails.emailfolder', verbose_name='Email Folder')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Tags associated with this email folder.', through='user_tags.UserTaggedItem', to='user_tags.UserTag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Email Folder Personalization',
                'verbose_name_plural': 'Email Folder Personalizations',
            },
        ),
        migrations.CreateModel(
            name='EmailPersonalization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, default='', help_text='Personal notes about this email.', verbose_name='Notes')),
                ('importance_level', models.IntegerField(blank=True, help_text='Personal importance level of this email.', null=True, verbose_name='Importance Level')),
                ('email', models.OneToOneField(editable=False, help_text='The email associated with this personalization.', on_delete=django.db.models.deletion.CASCADE, related_name='personalization', to='emails.email', verbose_name='Email')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='Tags associated with this email.', through='user_tags.UserTaggedItem', to='user_tags.UserTag', verbose_name='Tags')),
            ],
        ),
    ]
