# Generated by Django 5.2.8 on 2025-12-01 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server_address', models.CharField(help_text='The address of the Exchange server.', max_length=255, verbose_name='Server Address')),
                ('username', models.CharField(help_text='The username for the Exchange account.', max_length=255, verbose_name='Username')),
                ('email_address', models.EmailField(help_text='The email address associated with the Exchange account.', max_length=254, verbose_name='Email Address')),
                ('password_encrypted', models.BinaryField(help_text='The encrypted password for the Exchange account.', verbose_name='Encrypted Password')),
            ],
            options={
                'verbose_name': 'Exchange Account',
                'verbose_name_plural': 'Exchange Accounts',
            },
        ),
        migrations.CreateModel(
            name='ExchangeEmailAccount',
            fields=[
                ('emailaccount_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='emails.emailaccount')),
                ('exchange_account', models.OneToOneField(editable=False, help_text='The linked Exchange account.', on_delete=django.db.models.deletion.CASCADE, related_name='email_account', to='exchange.exchangeaccount', verbose_name='Exchange Account')),
            ],
            options={
                'verbose_name': 'Exchange Email Account',
                'verbose_name_plural': 'Exchange Email Accounts',
            },
            bases=('emails.emailaccount',),
        ),
    ]
